export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const ADD_PRODUCTS = "ADD_PRODUCT";
export const ADD_PRODUCTS_ERROR = "ADD_PRODUCT_ERROR";
export const DEL_PRODUCTS = "DEL_PRODUCTS";
export const DEL_PRODUCTS_ERROR = "DEL_PRODUCTS_ERROR";
export const EDIT_PRODUCTS = "EDIT_PRODUCTS";
export const EDIT_PRODUCTS_ERROR = "EDIT_PRODUCTS_ERROR";